Switch to new endpoint and require HTTPS
maxmind/geoipupdate-legacy pull request #103
Opened 2018-08-02 21:28 UTC by oschwald

2018-08-03 18:49 UTC, horgh requested changes
Good cleanup. Not as big a change as I somehow expected!

2018-08-03 18:49 UTC, horgh commented on bin/geoipupdate.c
> +    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 2L);
Wow, those were some less than great defaults.

Should we check the return value of these calls? Not that I expect they'd ever fail. Looks like one was failing before though and we never realized it! (VERIFYHOST being set to 1)

Ah, I see we generally don't elsewhere.

2018-08-03 18:49 UTC, horgh commented on bin/geoipupdate.c
> +        in_mem_s_delete(mem);
We should free `url` here too.

2018-08-03 18:49 UTC, horgh commented on bin/geoipupdate.c
>      if (status < 200 || status >= 300) {
I wonder if we should require 200 at this point.

2018-08-03 18:49 UTC, horgh commented on bin/geoipupdate.c
> +    exit_if(n < 0 || n >= 10,
Nice. Learned something about checking snprintf!

Hmm, I think we'd only have a useful errno in the < 0 case though.

2018-08-03 18:49 UTC, horgh commented on bin/geoipupdate.c
> +    curl_easy_setopt(curl, CURLOPT_USERNAME, account_id);
If we want to not use an account or license key, such as for a free database, what should we do? Currently the server requires valid credentials if they're provided. geoipupdate2 right now will not send username/password for free ones. I'm not sure that's the best solution. We could ignore account ID 0 I suppose, either here or on the server.

2018-08-03 19:05 UTC, oschwald commented on bin/geoipupdate.c
> +    curl_easy_setopt(curl, CURLOPT_USERNAME, account_id);
Ahh, good point. I will fix that so it isn't set.

2018-08-03 20:00 UTC, oschwald commented on bin/geoipupdate.c
> +    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 2L);
I think the primary reason an error would be returned is if the library didn't know about an option. Presumably, this isn't possible given that we are using the constants it provides. The other reason would be if someone explicitly disable an option at compile time. We could check for this, but I am not sure it is worth it especially given that this will hopefully be one of the last releases of this implementation.

2018-08-03 20:02 UTC, oschwald commented on bin/geoipupdate.c
> +    curl_easy_setopt(curl, CURLOPT_USERNAME, account_id);
So I copied what `geoipupdate2` does and used the `GeoLite2-` prefix. However, this doesn't sit completely well with be as it seems possible that we will release other free databases in the future. I almost checked to see if the account ID and license key were set to non-zero values until I saw `geoipupdate2` did this.

2018-08-03 20:32 UTC, horgh commented on bin/geoipupdate.c
> +    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 2L);
Yeah, as is seems okay.

2018-08-03 20:44 UTC, horgh commented on bin/geoipupdate.c
> +    curl_easy_setopt(curl, CURLOPT_USERNAME, account_id);
It's a good point about the naming decision not being future proof. Account ID being 0 is better in that regard. Either here or on the server. Though there's also the question of older configs that may have things other than 0, presumably.

2018-08-03 22:41 UTC, oschwald commented on bin/geoipupdate.c
> +    curl_easy_setopt(curl, CURLOPT_USERNAME, account_id);
I think we used to document that you could use `999999` for free databases. I am not sure where we documented it or how common it was. I see two requests with it in the past day. I think I would be ok listing that as a breaking change and requiring either a valid account ID, no account ID, or 0.

2018-08-04 18:18 UTC, horgh commented on bin/geoipupdate.c
> +    curl_easy_setopt(curl, CURLOPT_USERNAME, account_id);
That seems good!

2018-08-07 17:27 UTC, horgh approved these changes

2018-08-07 17:27 UTC, merged