Improve error reporting when non-HTTP 200 response
maxmind/geoipupdate-legacy pull request #56
Opened 2017-05-23 21:02 UTC by horgh

Currently in non-HTTP 200 responses we report by saying only that there is an unexpected HTTP status. The body contains a message. We write it out to stderr now.

This also updates `geoipupdate` to no longer inspect the body to determine whether it contains a message. In the case of no updates being available, we still receive HTTP 200, but we now check for this by examining the `X-Database-MD5` header. This simplifies the handling of the response body as we can now expect it to always be gzip data.

This also includes some small cleanups.

2017-05-24 15:12 UTC, oschwald requested changes
Looks reasonable. I had a few small comments.

2017-05-24 15:12 UTC, oschwald commented on bin/functions.c
> +    if (NULL == file || strlen(file) == 0) {
I am not sure Yoda conditions are really necessary anymore. Modern compilers should catch typos.

2017-05-24 15:12 UTC, oschwald commented on bin/functions.c
> +            bufsz == 0) {
Could you run `./dev/bin/uncrustify-all.sh` on this code?

2017-05-24 15:12 UTC, oschwald commented on bin/Makefile.am
> +TESTS = functions_test
We should update the Travis config to run these.

2017-05-24 15:12 UTC, oschwald commented on bin/geoipupdate.c
> +    memset(hex_digest2, 0, 33);
You could just initialize these to the zero array:

```c
char hex_digest[33] = {0}, hex_digest2[33] = {0};
```

2017-05-24 15:12 UTC, oschwald commented on bin/geoipupdate.c
> +    memset(hex_digest2, 0, 33);
You could just initialize these:

```c
memset(hex_digest, 0, 33);
memset(hex_digest2, 0, 33);
```

Same comment below too.

2017-05-24 17:10 UTC, horgh commented on bin/functions.c
> +    if (NULL == file || strlen(file) == 0) {
Wow, funny name for that style. I hadn't heard that name for it before!

Yeah, I'm not a fan of this style myself, but it appeared to be used in several locations in this code already. Although this code in general may not be something we want to be consistent with.

I'll adjust these.

This brings up another point: Should we collect some stuff like this into a C standards document? I know we talked about it not being so necessary yet, but some suggestions like this could help others. I was also thinking about bringing up use of `const`, both whether to use it where possible (as you can see I like it), and its position (I know some people prefer e.g. `const int` vs `int const`).

2017-05-24 17:14 UTC, oschwald commented on bin/functions.c
> +    if (NULL == file || strlen(file) == 0) {
Starting a C style guide with basic stuff like this sounds good to me. We can start small and expand as stuff comes up.

2017-05-24 17:31 UTC, horgh commented on bin/functions.c
> +            bufsz == 0) {
Yep. I also updated README.dev to mention that!

2017-05-24 17:40 UTC, horgh commented on bin/Makefile.am
> +TESTS = functions_test
Sounds good. How can I do that?

Related to this, would you prefer we used a more standard way of testing here? I just went with using `assert()` as you can see, which is fairly simple. I noticed that we use `libtap` in `libmaxminddb`. It would mean a dependency, but consistency might be worth it.

2017-05-24 17:48 UTC, horgh commented on bin/geoipupdate.c
> +    memset(hex_digest2, 0, 33);
Good point. I was not aware that that syntax filled the entire array. Thanks for the tip!

2017-05-24 18:16 UTC, horgh commented on bin/functions.c
> +    if (NULL == file || strlen(file) == 0) {
Cool. I'll write a draft later and send it to you!

2017-05-24 18:53 UTC, oschwald commented on bin/Makefile.am
> +TESTS = functions_test
I am ok with the asserts. I don't think there is a reason to change the now.

2017-05-24 18:57 UTC, oschwald commented on bin/Makefile.am
> +			  -std=c99 -Wall -Wextra -Werror
I don't think we should enable `-Werror` by default as people compile on all sorts of compilers and some of them will emit warnings.

2017-05-24 19:01 UTC, horgh commented on bin/Makefile.am
> +			  -std=c99 -Wall -Wextra -Werror
Ah good point. Do you think we should drop `-std=c99` here too for similar reasons?

2017-05-24 19:09 UTC, oschwald commented on bin/Makefile.am
> +			  -std=c99 -Wall -Wextra -Werror
I believe we set `-std=c99` on `libmaxminddb` and have not run into any complaints yet. I think it is safe to leave that.

2017-05-25 00:31 UTC, horgh commented
I just rebased after the OSX merge.

2017-05-25 14:30 UTC, merged