Improve error messages
maxmind/geoipupdate-legacy pull request #84
Opened 2017-11-21 19:25 UTC by oschwald

2017-11-21 23:45 UTC, horgh requested changes
A good step forward!

I've mostly got questions around whether errno is set in a few cases!

2017-11-21 23:45 UTC, horgh commented on bin/geoipupdate.c
> +    exit_if(rc == -1, "Error calling vasprintf: %s\n", strerror(errno));
Hmm, will vasprintf() actually set errno? Normally I'd go by what the man page says and I don't see it saying it does for this function.

2017-11-21 23:45 UTC, horgh commented on bin/geoipupdate.c
> +    exit_if(!ptr, "Error allocating memory: %s\n", strerror(errno));
If we were to be very pedantic, I'm not sure we can guarantee `calloc()` will set errno. C99 doesn't require it, at least. Maybe this is ugly, but in the past I've just done `strerror(ENOMEM)` for such cases. It looks like there are some existing cases of this as well.

2017-11-21 23:45 UTC, horgh commented on bin/geoipupdate.c
> +    exit_if(mem == NULL, "Error reallocating memory: %s\n", strerror(errno));
My comment about `calloc()` applies to `realloc()`

2017-11-21 23:45 UTC, horgh commented on bin/geoipupdate.c
> +    exit_if(ferror(fh), "Unable to read %s: %s\n", fname, strerror(errno));
Hmm, this is another case I'm not sure we get `errno` set.

2017-11-21 23:45 UTC, horgh commented on bin/geoipupdate.c
> +        exit_if(c < 0, "Unable to write digest: %s\n", strerror(errno));
Likewise, does `snprintf()` set `errno`?

2017-11-21 23:45 UTC, horgh commented on bin/geoipupdate.c
> +                    strerror(errno));
I don't think `fwrite()` will set `errno`

2017-11-21 23:45 UTC, horgh commented on bin/geoipupdate.c
> +    exit_if(-1 == fclose(fhw), "Error closing stream: %s\n", strerror(errno));
Interesting, the docs say `fclose()` does set `errno`. At least there is consistency!

2017-11-21 23:45 UTC, horgh commented on bin/geoipupdate_s.c
>      memset(gu, 0, size);
We don't need to memset now I think

2017-11-22 00:07 UTC, oschwald commented on bin/geoipupdate.c
> +    exit_if(rc == -1, "Error calling vasprintf: %s\n", strerror(errno));
All of the POSIX printf functions set errno:

http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html

For `vasprintf()`, I checked both FreeBSD and glibc. Both set it.

2017-11-22 00:08 UTC, oschwald commented on bin/geoipupdate.c
> +    exit_if(!ptr, "Error allocating memory: %s\n", strerror(errno));
In all modern Unixes, this should be set properly. I double checked on Windows and it appears it gets set there too.

From the `calloc` man page:

       SUSv2 requires malloc(), calloc(), and realloc() to set errno to ENOMEM upon failure.  Glibc assumes that this is done (and the glibc versions
       of these routines do this); if you use a private malloc implementation that does not set errno, then certain library routines may fail without
       having a reason in errno.

Is there a particular implementation that you are concerned about?

2017-11-22 00:10 UTC, oschwald commented on bin/geoipupdate.c
> +    exit_if(ferror(fh), "Unable to read %s: %s\n", fname, strerror(errno));
`fread` appears to set errno: http://pubs.opengroup.org/onlinepubs/009695399/functions/fread.html

2017-11-22 00:10 UTC, oschwald commented on bin/geoipupdate.c
> +        exit_if(c < 0, "Unable to write digest: %s\n", strerror(errno));
See above.

2017-11-22 00:10 UTC, oschwald commented on bin/geoipupdate_s.c
>      memset(gu, 0, size);
Thanks! I missed that.

2017-11-22 00:36 UTC, horgh commented on bin/geoipupdate.c
> +    exit_if(rc == -1, "Error calling vasprintf: %s\n", strerror(errno));
Much better docs than the man page. I'll have to remember to look there.

I don't think this one is POSIX, is it? It sounds like it's okay to expect it be set anyway though.

2017-11-22 00:37 UTC, horgh commented on bin/geoipupdate.c
> +    exit_if(!ptr, "Error allocating memory: %s\n", strerror(errno));
No, I mainly went by what you pasted and it not being specified in the standard.

2017-11-22 00:39 UTC, horgh commented on bin/geoipupdate.c
> +    exit_if(ferror(fh), "Unable to read %s: %s\n", fname, strerror(errno));
Oh good.

2017-11-22 00:42 UTC, horgh commented on bin/geoipupdate.c
> +    exit_if(!ptr, "Error allocating memory: %s\n", strerror(errno));
We have the same situation where [POSIX says](http://pubs.opengroup.org/onlinepubs/009695399/functions/calloc.html) it should be set, so that's another point in favour!

2017-11-22 01:06 UTC, horgh approved these changes

2017-11-22 01:06 UTC, horgh commented
I'm happy to merge it. I'm just going to wait on the Travis build.

2017-11-22 01:14 UTC, merged